# This file is required for pnpm cache setup in GitHub Actions.
# The setup-node action with cache: 'pnpm' requires a valid workspace file.
# This is a single-package project, not a monorepo.
packages:
  - '.'

# Allow these dependencies to run install scripts (for native compilation)
# - bcrypt: Password hashing (native bindings)
# - esbuild: JavaScript bundler (native binaries)
# - protobufjs: Protocol buffers (may need native compilation)
# - sharp: Image processing (native binaries for libvips)
# - unrs-resolver: Module resolver (native bindings)
onlyBuiltDependencies:
  - bcrypt
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
