/**
 * Financial Disclaimer Page
 *
 * Story 9.4: Financial Disclaimers
 * AC-9.4.5: Disclaimer accessible anytime from footer link at /disclaimer
 * AC-9.4.6: Includes algorithm transparency section
 *
 * Static page showing the full disclaimer text and algorithm transparency.
 */

import { Metadata } from "next";
import Link from "next/link";
import { AlertTriangle, ArrowLeft, Info, Calculator, Database } from "lucide-react";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Financial Disclaimer | Investments Planner",
  description:
    "Important information about how Investments Planner works and the nature of investment recommendations.",
};

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-background">
      <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
        {/* Back to Dashboard Link */}
        <div className="mb-8">
          <Button variant="ghost" asChild className="gap-2">
            <Link href="/dashboard">
              <ArrowLeft className="h-4 w-4" />
              Back to Dashboard
            </Link>
          </Button>
        </div>

        {/* Header */}
        <header className="mb-12 text-center">
          <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-amber-100 dark:bg-amber-950">
            <AlertTriangle className="h-8 w-8 text-amber-600 dark:text-amber-400" />
          </div>
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Financial Disclaimer</h1>
          <p className="mt-4 text-lg text-muted-foreground">
            Important information about the nature of this application
          </p>
        </header>

        {/* Main Disclaimer Content */}
        <section className="mb-12 space-y-6">
          <div className="rounded-lg border border-amber-200 bg-amber-50 p-6 dark:border-amber-900 dark:bg-amber-950/50">
            <p className="text-center text-xl font-semibold text-amber-800 dark:text-amber-200">
              This is NOT financial advice.
            </p>
          </div>

          <div className="prose prose-gray max-w-none dark:prose-invert">
            <p>
              Investments Planner is a portfolio management tool that provides investment
              suggestions based on <strong>your configured criteria</strong> and market data. The
              recommendations generated by this application are{" "}
              <strong>mathematical calculations</strong>, not professional guidance.
            </p>

            <h2>Key Points to Understand</h2>
            <ul>
              <li>
                <strong>Recommendations are calculations:</strong> All suggestions are based on
                algorithms that use the scoring criteria you define, combined with publicly
                available market data.
              </li>
              <li>
                <strong>Past performance is not indicative of future results:</strong> Historical
                data and past scores do not guarantee future investment performance.
              </li>
              <li>
                <strong>Consult a professional:</strong> Always consult a qualified financial
                advisor before making investment decisions. This tool is designed to assist your
                decision-making, not replace professional advice.
              </li>
              <li>
                <strong>You are responsible:</strong> You are solely responsible for your investment
                choices. The creators of this application assume no liability for any financial
                losses or gains resulting from the use of this tool.
              </li>
            </ul>
          </div>
        </section>

        {/* Algorithm Transparency Section */}
        <section className="mb-12 space-y-6">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-100 dark:bg-blue-950">
              <Info className="h-5 w-5 text-blue-600 dark:text-blue-400" />
            </div>
            <h2 className="text-2xl font-bold">Algorithm Transparency</h2>
          </div>

          <p className="text-muted-foreground">
            We believe in transparency about how our recommendations work. Here&apos;s how the
            system operates:
          </p>

          <div className="grid gap-6 sm:grid-cols-2">
            {/* User-Configured Criteria */}
            <div className="rounded-lg border bg-card p-6">
              <div className="mb-4 flex items-center gap-3">
                <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10">
                  <Calculator className="h-4 w-4 text-primary" />
                </div>
                <h3 className="font-semibold">User-Configured Criteria</h3>
              </div>
              <p className="text-sm text-muted-foreground">
                You define the scoring criteria that matter to you. This includes metrics like P/E
                ratio thresholds, dividend yields, market capitalization requirements, and more.
                Your investment philosophy drives the recommendations.
              </p>
            </div>

            {/* Market Data */}
            <div className="rounded-lg border bg-card p-6">
              <div className="mb-4 flex items-center gap-3">
                <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10">
                  <Database className="h-4 w-4 text-primary" />
                </div>
                <h3 className="font-semibold">Market Data Sources</h3>
              </div>
              <p className="text-sm text-muted-foreground">
                We fetch fundamental data and prices from reputable financial data providers. This
                data is cached and refreshed regularly to provide timely information while
                respecting API limits.
              </p>
            </div>
          </div>

          <div className="prose prose-gray max-w-none dark:prose-invert">
            <h3>How Recommendations Are Generated</h3>
            <ol>
              <li>
                <strong>Score Calculation:</strong> Each asset in your portfolio (and potential
                additions) is scored based on your defined criteria. Points are awarded or deducted
                based on how the asset&apos;s fundamentals compare to your thresholds.
              </li>
              <li>
                <strong>Allocation Analysis:</strong> Your current portfolio allocation is compared
                to your target allocation ranges for each asset class.
              </li>
              <li>
                <strong>Priority Ranking:</strong> Assets are prioritized based on a combination of
                their score and how under-allocated their asset class is relative to your targets.
              </li>
              <li>
                <strong>Investment Distribution:</strong> Your investable capital is distributed to
                assets based on priority, respecting minimum allocation values and asset count
                limits you&apos;ve configured.
              </li>
            </ol>

            <h3>What We Don&apos;t Do</h3>
            <ul>
              <li>We don&apos;t predict market movements or future asset performance</li>
              <li>We don&apos;t consider tax implications of investment decisions</li>
              <li>We don&apos;t account for your complete financial situation</li>
              <li>We don&apos;t provide personalized financial planning</li>
            </ul>
          </div>
        </section>

        {/* Data Usage Notice */}
        <section className="mb-12">
          <div className="rounded-lg border bg-muted/50 p-6">
            <h3 className="mb-4 font-semibold">Data and Privacy</h3>
            <p className="text-sm text-muted-foreground">
              Your portfolio data and configurations are stored securely and are only accessible to
              you. We do not share your personal investment information with third parties. Market
              data fetched for your portfolio is used solely to provide you with scores and
              recommendations.
            </p>
          </div>
        </section>

        {/* Footer Navigation */}
        <footer className="border-t pt-8 text-center">
          <p className="mb-4 text-sm text-muted-foreground">
            By using Investments Planner, you acknowledge that you have read and understood this
            disclaimer.
          </p>
          <div className="flex justify-center gap-4">
            <Button asChild>
              <Link href="/dashboard">Return to Dashboard</Link>
            </Button>
          </div>
        </footer>
      </div>
    </main>
  );
}
